# Permalinks
permalink:        pretty

# Kramdown settings
kramdown:
  hard_wrap: true

# Setup
title:            www.bochen.dk
url:              http://www.bochen.dk
baseurl:          /
author:
  name:           bochen
  url:            http://www.bochen.dk
