# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            bochen.dk
tagline:          just another website
url:              http://bochen.dk
baseurl:          /
author:
  name:           Bo Chen
  url:            http://bochen.dk
