# Permalinks
permalink:        pretty

# Kramdown settings
kramdown:
  hard_wrap: true

# Setup
title:            www.bochen.dk
tagline:          just another website
url:              http://www.bochen.dk
baseurl:          /
author:
  name:           Bo Chen
  url:            http://www.bochen.dk
